/*
 * DUST DASH 画面の文字（日本語・英語）
 */
(function (global) {
  'use strict';
  var DD = global.DD = global.DD || {};

  DD.TEXT = {
    ja: {
      subtitle: '砂けむりダッシュ',
      tapToStart: 'タップでスタート',
      keyHint: 'スペースキーでもOK',
      hintJump: 'タップでジャンプ！',
      hintStomp: '上から踏んで食べると加速＆スタミナ回復！',
      exhausted: 'ヘトヘト…',
      hintDouble: '空中でもう一度タップで2段ジャンプ',
      hintCombo: '着地せずに踏み続けるとコンボ！',
      hintTall: '2段ジャンプで飛び越えろ！',
      hintDuck: 'ジャンプしないで下をくぐれ！',
      combo: '{n}コンボ！',
      milestone: '{n} m 突破！',
      stage: 'STAGE {n}',
      whirl: 'つむじ風！',
      perfect: 'パーフェクト！',
      gem_sapphire: 'サファイア',
      gem_emerald: 'エメラルド',
      gem_ruby: 'ルビー',
      gems: '宝石',
      stage_desert: '朝の砂漠',
      stage_canyon: '赤い峡谷',
      stage_sunset: '夕焼けのメサ',
      stage_night: '星空の砂丘',
      stage_oasis: '夜明けのオアシス',
      finalStage: 'FINAL STAGE',
      goal: 'ゴール！',
      escaped: 'にげきった！',
      clears: 'クリア',
      endCap1: '朝日と オアシスが 見えた！',
      endCap2: 'タカは 池に ドボン！',
      endCap3: 'びしょぬれで あきらめたみたい…',
      harder: 'だんだん手ごわくなるぞ',
      comboHud: 'コンボ',
      maxCombo: '最大コンボ',
      caught: 'つかまった！',
      topSpeed: '最高時速',
      distance: '距離',
      snakes: 'ヘビ',
      retry: 'もう一度',
      credit: 'Tanuki Box',
      fever: 'フィーバー！',
      startDash: 'スタートダッシュ！',
      hintFever: 'ゲージがたまるとフィーバー！',
      coinsEarned: 'コイン',
      picked: '拾った',
      distBonus: '距離ボーナス',
      luckBonus: '金運',
      newRecord: '新記録！',
      best: 'ベスト',
      shop: '強化',
      back: 'もどる',
      start: 'スタート',
      story: 'ストーリー',
      skip: 'スキップ',
      storyCap1: 'ここは 夜明けの砂漠。',
      storyCap2: '……ん？',
      storyCap3: 'タカに ねらわれた！',
      storyTitle: '食べて、走って、\n逃げきれ！',
      max: 'MAX',
      up_stamina: 'スタミナ',
      up_stamina_d: 'スタミナの減りがおそくなる',
      up_dash: 'スタートダッシュ',
      up_dash_d: 'スタート直後に無敵でダッシュ',
      up_ukemi: '受け身',
      up_ukemi_d: 'ぶつかったときのダメージが減る',
      up_glutton: '食いしん坊',
      up_glutton_d: '食べたときの回復とフィーバーが増える',
      up_luck: '金運',
      up_luck_d: 'もらえるコインが増える'
    },
    en: {
      subtitle: 'Outrun the hawk!',
      tapToStart: 'TAP TO START',
      keyHint: 'or press SPACE',
      hintJump: 'TAP TO JUMP!',
      hintStomp: 'STOMP PREY: SPEED UP & REFILL!',
      exhausted: 'EXHAUSTED...',
      hintDouble: 'TAP AGAIN IN THE AIR TO DOUBLE JUMP',
      hintCombo: 'KEEP STOMPING FOR A COMBO!',
      hintTall: 'DOUBLE JUMP OVER IT!',
      hintDuck: "DON'T JUMP. RUN UNDER IT!",
      combo: '{n} COMBO!',
      milestone: '{n} m!',
      stage: 'STAGE {n}',
      whirl: 'WHIRLWIND!',
      perfect: 'PERFECT!',
      gem_sapphire: 'Sapphire',
      gem_emerald: 'Emerald',
      gem_ruby: 'Ruby',
      gems: 'GEMS',
      stage_desert: 'Morning Desert',
      stage_canyon: 'Red Canyon',
      stage_sunset: 'Sunset Mesas',
      stage_night: 'Starry Dunes',
      stage_oasis: 'Dawn Oasis',
      finalStage: 'FINAL STAGE',
      goal: 'GOAL!',
      escaped: 'ESCAPED!',
      clears: 'CLEARS',
      endCap1: 'The oasis at sunrise!',
      endCap2: 'SPLASH! The hawk fell in!',
      endCap3: 'Soaked, it gave up...',
      harder: 'IT GETS TOUGHER...',
      comboHud: 'COMBO',
      maxCombo: 'BEST COMBO',
      caught: 'CAUGHT!',
      topSpeed: 'TOP SPEED',
      distance: 'DISTANCE',
      snakes: 'SNAKES',
      retry: 'RETRY',
      credit: 'Tanuki Box',
      fever: 'FEVER!',
      startDash: 'START DASH!',
      hintFever: 'FILL THE GAUGE FOR FEVER!',
      coinsEarned: 'COINS',
      picked: 'Picked',
      distBonus: 'Distance',
      luckBonus: 'Luck',
      newRecord: 'NEW RECORD!',
      best: 'BEST',
      shop: 'UPGRADES',
      back: 'BACK',
      start: 'START',
      story: 'STORY',
      skip: 'SKIP',
      storyCap1: 'Dawn in the desert.',
      storyCap2: '...Huh?',
      storyCap3: 'A hawk is hunting you!',
      storyTitle: 'EAT. RUN.\nESCAPE!',
      max: 'MAX',
      up_stamina: 'Stamina',
      up_stamina_d: 'Stamina drains slower',
      up_dash: 'Start Dash',
      up_dash_d: 'Invincible dash at the start',
      up_ukemi: 'Tough Fall',
      up_ukemi_d: 'Take less damage from hits',
      up_glutton: 'Big Eater',
      up_glutton_d: 'More refill and fever from prey',
      up_luck: 'Lucky Coins',
      up_luck_d: 'Earn more coins'
    }
  };
})(window);
